Update fork repository
cvlabmiet/convex_hull_bst pull request #2
Opened 2018-05-28 20:07 UTC by DimaWoogy

Changes:
C++:
- BST hull algorithm is rewritten to use CGAL Point_2 class. Minor refactoring is made.
- Algorithms measuring is changed to be more precise.
Python:
- Fix defect more convex hull points than we should. Generate points inside of the hull itself, not inside of the circle.
- Add charts from classic comparison.

2018-05-29 15:05 UTC, rgolovanov commented
@DimaWoogy просто нужно через  собаку логин написать

2018-05-29 15:37 UTC, rgolovanov commented
@DimaWoogy посмотрел. Сильно закапываться в ревью алгоритмов не могу - потрачу много времени. И не вижу большого смысла, так есть тесты.

Исправь формальные замечания и этого будет достаточно.
Ещё желательно избавиться от лишних зависимостей - убрать `boost`. Тогда `bsthull.h` можно будет легко использовать в других проектах.

ты смотрел, есть ли шанс положить этот алгоритм в `CGAL` ?

2018-06-03 21:44 UTC, DimaWoogy commented
@rgolovanov Пара вопросов.
"Исправь формальные замечания и этого будет достаточно" - Какие формальные замечания?
"Ещё желательно избавиться от лишних зависимостей - убрать boost" - Сам CGAL зависит от boost-а, но да, из моего кода лучше его убрать. Сделаю.
"ты смотрел, есть ли шанс положить этот алгоритм в CGAL?" - Сейчас используется класс точки Point_2 из CGAL. Но все текущие алгоритмы из CGAL написаны как алгоритмы STL, что не очень подходит для нашего бинарного дерева, которое просто возвращается как результат. То есть наш алгоритм по сути представляет собой больше структуру данных, поэтому не похож на остальные из CGAL. Возможно подобные алгоритмы в CGAL есть, но вроде не в области выпуклых оболочек.

2018-06-08 06:51 UTC, rgolovanov commented
@DimaWoogy формальные - те, которые я написал. Там ведь по существу мало...

2018-06-11 19:41 UTC, rgolovanov requested changes
Видимо, я забыл сделать submit всех замечаний :)

2018-06-11 19:41 UTC, rgolovanov commented on CMakeLists.txt
> +set(ALGO_HEADERS ${ALGO_DIR}/bsthull.h ${ALGO_DIR}/point.h)
заголовочные файлы не нужны для компиляции. можно убрать 
```cmake
include_directories(algorithms)
add_executable(main charts/main.cpp)
```

2018-06-11 19:41 UTC, rgolovanov commented on algorithms/bsthull.h
> +   // TODO: I never free singleton memory
что тут нужно исправить/допилить? из комментария не понятно

2018-06-11 19:41 UTC, rgolovanov commented on algorithms/bsthull.h
> +struct CyclicSet
было бы не плохо добавить минимальные комментарии к основным структурам

2018-06-11 19:41 UTC, rgolovanov commented on algorithms/bsthull.h
Во все файлы нужно добавить стандартные шапки:
* file
* brief
* author
* date

2018-06-11 19:41 UTC, rgolovanov commented on algorithms/bsthull.h
для кроссплатформенности не хватает `header guard`:

```cpp
#ifdef __BSTHULL_H
#define __BSTHULL_H
...
#endif // __BSTHULL_H
```

2018-06-11 21:59 UTC, DimaWoogy commented
@rgolovanov Замечания исправлены.

2018-06-11 22:20 UTC, rgolovanov requested changes
Ещё немного можно улучшить.

Оказывается в мобильной версии сайта github нет кнопки для сабмита комментов ревью.

2018-06-11 22:20 UTC, rgolovanov commented on charts/main.cpp
> +template <class TFn, class... TArgs>
TArgs ещё актуален?

2018-06-11 22:20 UTC, rgolovanov commented on charts/run.py
>  import random
Прогони питоновский файл через pycodestyle + можно эту проверку вынести в трэвис

2018-06-11 22:20 UTC, rgolovanov commented on CMakeLists.txt
> +add_executable(randomtest test/randomtesting.cpp)
Вообще не желательно смешивать бинарники в одном cmake файле. Лучше на каждый бинарник иметь свой cmakelists.

В этом файле просто пишешь add_subdirectory(tests), а в папке tests создаёшь отдельный cmakelists для сборки randomtest.

А ещё лучше (структурно) тут иметь 3 cmake файла: главный, папка с библиотекой алгоритмов, папка с тестами

Но это не критично.

2018-06-24 11:35 UTC, DimaWoogy commented
@rgolovanov Спасибо за замечания. Вроде поправил всё. Круче стало:)

2018-06-28 08:19 UTC, rgolovanov approved these changes

2018-06-28 08:20 UTC, merged